### ISSUE TITLE
no package called ‘doParallel’

### ISSUE THREAD

**Issue by kforthman** [kforthman/caretStack#3]
Now it is giving me the following error:

Error in library(doParallel) : there is no package called ‘doParallel’
Calls: source ... withVisible -> eval -> eval -> predict_one -> library
In addition: Warning message:
In predict_one(this_data, "lme_slope_simple", c("all_vars-touse_rmSTD_np.csv"),  :
  17 participants have been removed because more than 30% of their predictor variables are missing. These are the participants that were removed:
AJ196
AJ196
AJ468
AJ855
AL596
AL627
AM831
AN574
AO065
AO580
AO580
AP321
AP366
AP663
AQ978
AR118
AS590
Execution halted

_Originally posted by @rssmith33 in https://github.com/kforthman/caretStack/issues/2#issuecomment-525786717_

**Comment by kforthman** [comment]
There was another problem where a library call of doParallel was in the `predict_one` function. The proper import method has now been implemented.

**Comment by rssmith33** [comment]
I just tried it and it still gave me the same error…

**Comment by kforthman** [comment]
Please try installing 'doParallel' on the server. If you get an error, please copy the entire error in your next comment.

Here is how to install it through the terminal:
```
# first, log onto the server through the terminal
ssh submit0
# (type your password and hit 'enter')
module load R
R
install.packages('doParallel')
```

**Comment by rssmith33** [comment]
I successfully installed the package through the terminal, and I can load the library through the terminal. But I still got the same error when I try to run the analysis.

**Comment by kforthman** [comment]
Please try re-installing caretStack. Show me your input and output when you are finished so that I know it was installed correctly.

**Comment by rssmith33** [comment]
![Capture](https://user-images.githubusercontent.com/49658036/64053468-2035ee80-cb48-11e9-8f6e-457904c35891.JPG)

**Comment by kforthman** [comment]
Ok... I see the problem. See how it says 
```
Installing package into ‘/media/cephfs/homefolders/librad.laureateinstitute.org/rsmith/R/library’
```
It should say
```
Installing package into ‘/media/cephfs/homefolders/librad.laureateinstitute.org/rsmith/R/3.5.1’
```
Basically, it's not installing the package in the right place.

It looks like the patch from issue #1 still isn't working correctly. I'm not sure why. This is an issue that should really be solved at the IT level, but I will talk to Rayus on Tuesday and see what we can do in the meantime.

**Comment by GeethData** [comment]
install.packages(c("parallel","iterators", "foreach", "doParallel"))
Run that on R consol
