### ISSUE TITLE
ml problem

### ISSUE THREAD

**Issue by rssmith33** [kforthman/caretStack#4]
Hi Katie, I'm running into some problems getting the machine learning algorithm to work. I keep seeing the following at around 15 minutes in:

2: In nominalTrainWorkflow(x = x, y = y, wts = weights, info = trainInfo,  :
  There were missing values in resampled performance measures.

Any ideas?

**Comment by kforthman** [comment]
Would you give me a more detailed description of what you are trying to do? What is the line of code that is giving you issues? Are you getting this error in the err.log file? Does this message end the run, or does it continue?

Have you tried imputation to make sure there are no missing values?

**Comment by kforthman** [comment]
It imputes the predictors automatically, not the target. You may want to remove the the participants that are missing the target variable rather than impute.

I thought what you had tried previously worked? Are you doing anything differently this time?

**Comment by kforthman** [comment]
I am attaching the files you emailed me on this thread. I would appreciate you sending me files this way in the future. 

Are you sure this warning ended your run? Warnings do not usually end the script, only errors. Would you send me your out.log file?

[Archive.zip](https://github.com/kforthman/caretStack/files/3708309/Archive.zip)

**Comment by rssmith33** [comment]
The out.log file is completely empty.

**Comment by kforthman** [comment]
I could not reproduce the issue with the code you sent me. Attaching my results.
[Archive.zip](https://github.com/kforthman/caretStack/files/3708490/Archive.zip)

Do you have a file named test.results.RData in your working directory?

Here are some things you might troubleshoot:
Please make sure you are using the most current version of caretStack. Double check that your file paths are all correct as well. Make sure that the time-stamp on your err.log file is not old.

**Comment by rssmith33** [comment]
There is a file named test.results.RData. But it only ran for 15 minutes or so.

**Comment by kforthman** [comment]
The ML can work pretty quickly on smaller datasets. Go ahead and run the summarize_one() function and let me know if your results are abnormal.

**Comment by kforthman** [comment]
Another reason that this is much faster than previously is that you only have 5 outer folds. We have used as many as 20 folds in the past. You can change this parameter by specifying the `nFolds.outer` argument in `predict_one()`.

**Comment by rssmith33** [comment]
When I try to knit it doesn't work:

Error in yaml::yaml.load(..., eval.expr = TRUE) : 
  Parser error: did not find expected <document start> at line 2, column 1
Calls: <Anonymous> ... parse_yaml_front_matter -> yaml_load -> <Anonymous>
Execution halted

**Comment by kforthman** [comment]
Please send me your .Rmd file.

**Comment by rssmith33** [comment]
[summary.zip](https://github.com/kforthman/caretStack/files/3708896/summary.zip)

**Comment by kforthman** [comment]
The header is formatted incorrectly. Remove the space on line 2, before `title: "HB_AI_g"`

**Comment by rssmith33** [comment]
Ugh. It still won't work because caretStack isn't installed on my personal copy of R. But it also won't let me install it because it won't install devTools because it won't install pkgBuild:

> library(devtools)
Loading required package: usethis
Error: package or namespace load failed for ‘devtools’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 there is no package called ‘pkgbuild’
> install.packages("pkgbuild")

  There is a binary version available but the source version is later:
         binary source needs_compilation
pkgbuild  1.0.5  1.0.6             FALSE

installing the source package ‘pkgbuild’

trying URL 'https://cran.rstudio.com/src/contrib/pkgbuild_1.0.6.tar.gz'
Content type 'application/x-gzip' length 29322 bytes (28 KB)
downloaded 28 KB

'\\isilon1\homefolders\rsmith\Documents\R\R-3.6.1' is not recognized as an internal or external command,
operable program or batch file.
Warning in install.packages :
  installation of package ‘pkgbuild’ had non-zero exit status

The downloaded source packages are in
	‘C:\Users\rsmith\AppData\Local\Temp\RtmpamlQ3O\downloaded_packages’
> library(pkgbuild)
Error in library(pkgbuild) : there is no package called ‘pkgbuild’

**Comment by kforthman** [comment]
I would try installing an earlier version of `pkgbuild`. The version I have on my computer is 1.0.3. Try
`install.packages("pkgbuild", version = "1.0.3")`

**Comment by rssmith33** [comment]
Still no luck...

**Comment by kforthman** [comment]
I think there may be something wrong with the directory it is trying to install the package to. Will you try installing another package and see if it gives you a similar error? For example, `install.packages("psych")`. Try that and show me the output.

If you would like to uninstall a package you already have and try to re-install it, you can uninstall by going to the 'Packages' tab in RStudio and clicking the 'x' next to the package you want to uninstall, located at the far right. Please give me the output from the console after you do this.

**Comment by kforthman** [comment]
Try this:
execute in the console
`.libPaths()`
Copy the first result

then in the console, execute
`install.packages("pkgbuild", lib = [paste here])`

**Comment by rssmith33** [comment]
> .libPaths()
[1] "\\\\isilon1/homefolders/RSmith/Documents/R/R-3.6.1/library"
> install.packages("pkgbuild", lib = ["\\\\isilon1/homefolders/RSmith/Documents/R/R-3.6.1/library"])
Error: unexpected '[' in "install.packages("pkgbuild", lib = ["
> install.packages("pkgbuild", lib = "\\\\isilon1/homefolders/RSmith/Documents/R/R-3.6.1/library")

  There is a binary version available but the source version is later:
         binary source needs_compilation
pkgbuild  1.0.5  1.0.6             FALSE

installing the source package ‘pkgbuild’

trying URL 'https://cran.rstudio.com/src/contrib/pkgbuild_1.0.6.tar.gz'
Content type 'application/x-gzip' length 29322 bytes (28 KB)
downloaded 28 KB

'\\isilon1\homefolders\rsmith\Documents'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.
'\\isilon1\homefolders\rsmith\Documents\R\R-3.6.1' is not recognized as an internal or external command,
operable program or batch file.
Warning in install.packages :
  installation of package ‘pkgbuild’ had non-zero exit status

The downloaded source packages are in
	‘C:\Users\rsmith\AppData\Local\Temp\RtmpiiiZJN\downloaded_packages’

**Comment by kforthman** [comment]
Now, would you please send me the input and output when you install a different package that you know works? For example, you could try the `psych` package.

**Comment by rssmith33** [comment]
> install.packages("pseudo")
also installing the dependencies ‘KMsurv’, ‘geepack’

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.6/KMsurv_0.1-5.zip'
Content type 'application/zip' length 129789 bytes (126 KB)
downloaded 126 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.6/geepack_1.2-1.zip'
Content type 'application/zip' length 987850 bytes (964 KB)
downloaded 964 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.6/pseudo_1.4.3.zip'
Content type 'application/zip' length 44312 bytes (43 KB)
downloaded 43 KB

package ‘KMsurv’ successfully unpacked and MD5 sums checked
package ‘geepack’ successfully unpacked and MD5 sums checked
package ‘pseudo’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\rsmith\AppData\Local\Temp\RtmpiiiZJN\downloaded_packages
>

**Comment by kforthman** [comment]
Now type 
`version`
and send me the output from that.

**Comment by rssmith33** [comment]
> version
               _                           
platform       x86_64-w64-mingw32          
arch           x86_64                      
os             mingw32                     
system         x86_64, mingw32             
status                                     
major          3                           
minor          6.1                         
year           2019                        
month          07                          
day            05                          
svn rev        76782                       
language       R                           
version.string R version 3.6.1 (2019-07-05)
nickname       Action of the Toes          
>
